language: clojure
lein: lein2
script: lein2 midje :print-facts
jdk:
  - oraclejdk7
branches:
  except:
    - gh-pages
env:
  global:
    - secure: "eRpg/alQ+1OTdhr1lcVSJyVU4eJ66ShffLDpnLV7+YZq9J29jwhgXdUHWALS\nsGQCNnty61Y1BvtRVQ46PCWHdXsk5pwgQidFPzVLQrcmnboEdKoM1fQzvery\ns2wYndL62jMhm3FachXTfHzpoNUcwU3dxr/To+U5E+q7r2Ua/Wk="
    - GEN_APIDOCS="lein2 with-profile doc do doc, marg"

after_success:
  - chmod a+x travis/post_build.sh
  - ./travis/post_build.sh

